name: GitHub-Profile-3D-Contrib

on:
  schedule: # 03:00 JST == 18:00 UTC
    - cron: "0 18 * * *"
  workflow_dispatch:

jobs:
  build:
    permissions:
      actions: write
      checks: write
      contents: write
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v2
      - uses: yoshi389111/github-profile-3d-contrib@0.6.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
    #   - uses: actions/setup-python@v2
    #     with:
    #       python-version: "3.9"
    #       architecture: "x64"
    #   - name: pip setting
    #     run: |
    #       python -m pip install --upgrade pip
    #   - name: run python
    #     working-directory: scripts
    #     run: |
    #       python updateReadme.py
    #       mv README.md ./../README.md
      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A .
          git commit -m "update by github action"
          git push
